// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eryjatgurpsajpvkglfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyeWphdGd1cnBzYWpwdmtnbGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1ODAyNDgsImV4cCI6MjA1NDE1NjI0OH0.6o4Uwz_2x2zZ7LqqAU3uFOJJN1h2gK3SRyTlQghmv7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);